const locations = [
  { id: 1, name: "A Coruña" },
  { id: 2, name: "Álava" },
  { id: 3, name: "Albacete" },
  { id: 4, name: "Alicante" },
  { id: 5, name: "Almería" },
  { id: 6, name: "Asturias" },
  { id: 7, name: "Ávila" },
  { id: 8, name: "Badajoz" },
  { id: 9, name: "Baleares" },
  { id: 10, name: "Barcelona" },
  { id: 11, name: "Burgos" },
  { id: 12, name: "Cáceres" },
  { id: 13, name: "Cádiz" },
  { id: 14, name: "Cantabria" },
  { id: 15, name: "Castellón" },
  { id: 16, name: "Ciudad Real" },
  { id: 17, name: "Córdoba" },
  { id: 18, name: "Cuenca" },
  { id: 19, name: "Girona" },
  { id: 20, name: "Granada" },
  { id: 21, name: "Guadalajara" },
  { id: 22, name: "Gipuzkoa" },
  { id: 23, name: "Huelva" },
  { id: 24, name: "Huesca" },
  { id: 25, name: "Jaén" },
  { id: 26, name: "La Rioja" },
  { id: 27, name: "Las Palmas" },
  { id: 28, name: "León" },
  { id: 29, name: "Lérida" },
  { id: 30, name: "Lugo" },
  { id: 31, name: "Madrid" },
  { id: 32, name: "Málaga" },
  { id: 33, name: "Murcia" },
  { id: 34, name: "Navarra" },
  { id: 35, name: "Ourense" },
  { id: 36, name: "Palencia" },
  { id: 37, name: "Pontevedra" },
  { id: 38, name: "Salamanca" },
  { id: 39, name: "Segovia" },
  { id: 40, name: "Sevilla" },
  { id: 41, name: "Soria" },
  { id: 42, name: "Tarragona" },
  { id: 43, name: "Santa Cruz de Tenerife" },
  { id: 44, name: "Teruel" },
  { id: 45, name: "Toledo" },
  { id: 46, name: "Valencia" },
  { id: 47, name: "Valladolid" },
  { id: 48, name: "Vizcaya" },
  { id: 49, name: "Zamora" },
  { id: 50, name: "Zaragoza" },
  { id: 51, name: "Ceuta" },
  { id: 52, name: "Melilla" },
];

export default locations;
